[package]
name = "day_09"
version = "0.1.0"
authors = ["Johannes Postma <9338178+jgmp@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
